apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qko468lqt-go
  janus-idp.io/tekton: qko468lqt-go
  backstage.io/kubernetes-id: qko468lqt-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qko468lqt-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
